source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

workspace 'AvocarrotSDKAdapters'
target 'AvocarrotSDKAdapters' do
    pod 'avocarrot-ios-sdk/NativeAssets', '~> 4.5.0-0'
    pod 'avocarrot-ios-sdk/Interstitial', '~> 4.5.0-0'
    pod 'avocarrot-ios-sdk/Banner', '~> 4.5.0-0'
    pod 'mopub-ios-sdk', '~> 4.13'
    pod 'Google-Mobile-Ads-SDK', '~> 7.19'
    pod 'SDWebImage'
    pod 'Fabric'
    pod 'Crashlytics'
end
